In [1]:
import numpy as np

In [14]:
P = [
    [1, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 1, 0, 0],
    [0, 0, 1, 0]
]

Q = [
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 0, 1, 0]
]

In [41]:
def distribution(matrix):
#     dist = np.zeros((len(matrix)+1, len(matrix[0])+1))
    dist = np.ones((len(matrix)+1, len(matrix[0])+1))
    dist[-1][-1] = 0
    def rec_sum(dist, matrix, i, j):
        if (i, j) == (len(matrix), 0):
            dist[i][j] = 0
        if dist[i][j] < 0:
            dist[i][j] = max(rec_sum(dist, matrix, i-1, j) + dist[i][j-1], rec_sum(dist, matrix, i, j-1) + dist[i][j])
        else:
            return dist[i][j]
    rec_sum(dist, matrix, 0, len(matrix))
    print(dist)

distribution(P)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0.]]


In [20]:
def to_permutation(matrix): # O(n^2)
    arr = np.zeros(len(matrix))
    for ix, i in enumerate(matrix):
        for jx, j in enumerate(i):
            arr[ix] = jx if j == 1 else arr[ix]
    return arr

In [18]:
def to_matrix(permutation): # O(n)
    matrix = np.zeros((len(permutation), max(permutation)+1))
    for ix, i in enumerate(permutation):
        matrix[ix][i] = 1
    return matrix

In [29]:
-np.eye((len(P)+1))

array([[-1., -0., -0., -0., -0.],
       [-0., -1., -0., -0., -0.],
       [-0., -0., -1., -0., -0.],
       [-0., -0., -0., -1., -0.],
       [-0., -0., -0., -0., -1.]])